### ISSUE TITLE
Reperire auth_token

### ISSUE THREAD

**Issue by aleeessio** [Leone25/bSmart-downloader#1]
Ciao, scusa il disturbo sono sempre io. Come faccio ad ottenere il token se sul sito di bsmart quando visualizzo il libro non mi lascia fare tasto destro > ispeziona?

**Comment by Leone25** [comment]
Ci sono vari alternative:
- prova tenendo premuto ctrl e cliccando col tasto dinistro dovrebbe comparirti il menu di contesto
- prova a premere ctrl + shift + i
- prova a premere f12
- nel menu in alto a destra del browser (3 pallini sotto la x per chiudere il browser) ci dovrebbe essere scritto altri strumenti > ispezziona pagina

Spero che almeno uno di questi metodi ti vada

**Comment by aleeessio** [comment]
> Ci sono vari alternative:
> - prova tenendo premuto ctrl e cliccando col tasto dinistro dovrebbe comparirti il menu di contesto
> - prova a premere ctrl + shift + i
> - prova a premere f12
> - nel menu in alto a destra del browser (3 pallini sotto la x per chiudere il browser) ci dovrebbe essere scritto altri strumenti > ispezziona pagina
> 
> Spero che almeno uno di questi metodi ti vada

Fatto, ha funzionato con ctrl + shift + i. Lo script fino ad ora funziona alla perfezione grazie ancora :)
