### ISSUE TITLE
Aiuto! 

### ISSUE THREAD

**Issue by fedeTrade** [Leone25/bSmart-downloader#10]
Gentilmente, potresti inviarmi un video che mostra come estrarre libri da bsmart e booktab, non sono troppo ferrata in questo e sto riscontrando diverse difficoltà. Te ne sarei grata e chiedo scusa per il disturbo.

**Comment by Leone25** [comment]
Per booktab puoi guardare l'inizio di [questo video](https://youtu.be/JYHoYqsxv88)

Per bsmart non ho video specifici, ma puoi provare a farmi domande sui problemi che riscontri e cercherò di aiutarti

**Comment by masteoo** [comment]
> Gentilmente, potresti inviarmi un video che mostra come estrarre libri da bsmart e booktab, non sono troppo ferrata in questo e sto riscontrando diverse difficoltà. Te ne sarei grata e chiedo scusa per il disturbo.

@fedeTrade ciao, sei riuscita? Io seguendo le istruzioni e con l'aiuto di Leone25 sono riuscito!

**Comment by fedeTrade** [comment]
@Leone25 Grazie, ci sono riuscita! 
Per il libri su bsmart ho seguito le tue istruzioni.
Per i libri Zanichelli (kitaboo) ho guardato il video.
 Soltanto per booktab purtroppo ho provato sia su MacOs ma da errore sul comando " pip ...... ", mentre su windows non mi permetteva di incollare il Cookie, non so se hai una soluzione.
Inoltre devo farti i complimenti @Leone25, sei proprio un salvatore!

**Comment by Leone25** [comment]
>  Soltanto per booktab purtroppo ho provato sia su MacOs ma da errore sul comando " pip ...... ", mentre su windows non mi permetteva di incollare il Cookie, non so se hai una soluzione.

Per incollare nel terminale o CTRL+V o tasto destro di solito funziona

**Comment by masteoo** [comment]
> @masteoo Si ci sono riuscita! Qualche problemino con booktab, ma con bSmart va benissimo!

🔝🔝🔝 ti va di condividerli se servissero anche a me? Che libri servirebbero invece a te? Che vedo se li ho

**Comment by Leone25** [comment]
chiedo gentilmente di non avere questo genere di conversazione qui, pubblicamente

**Comment by masteoo** [comment]
>  Si ci sono riuscita! Qualche problemino con booktab, ma con bSmart va benissimo!

🔝🔝🔝 @fedeTrade...
 posso chiederti una cosa su twitter o telegram?

**Comment by fedeTrade** [comment]
> > Soltanto per booktab purtroppo ho provato sia su MacOs ma da errore sul comando " pip ...... ", mentre su windows non mi permetteva di incollare il Cookie, non so se hai una soluzione.
> 
> Per incollare nel terminale o CTRL+V o tasto destro di solito funziona

Già provato ma non funziona. Il mio pc windows è un pò obsoleto per questo motivo ho usato il Mac. 
Su Mac esce: " zsh: command not found: pip " , ho pensato fosse un errore riguardante la versione ma non credo .

**Comment by Leone25** [comment]
https://duckduckgo.com/?q=pip+command+not+found+macbook
