### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by Anton893c** [Leone25/bSmart-downloader#12]
Faccio tutto come descritto. Quando incollo (devo premere più volte per farlo) dopo aver premuto invio lo script si chiude senza fare nulla. Il cookie che copio lo trovo in un file  .svg è corretto?

**Comment by Leone25** [comment]
Mi sembra assai strano, potresti darmi più dettagli o fare un video di ciò che fai

**Comment by JustOptimize** [comment]
> Faccio tutto come descritto. Quando incollo (devo premere più volte per farlo) dopo aver premuto invio lo script si chiude senza fare nulla. Il cookie che copio lo trovo in un file .svg è corretto?

Oddio, assolutamento no, devi andare su `https://my.bsmart.it`, premere F12, cliccare sulla sezione Cookie e copiare il valore assegnato a `_bsw_session_v1_production`
