### ISSUE TITLE
Problema nel terminale

### ISSUE THREAD

**Issue by ValeDeFra27** [Leone25/bSmart-downloader#16]
Scusate l'ignoranza, qualcuno sa dirmi perchè quando faccio click destro per incollare il cookie mi si incolla 50 volte?

![image](https://github.com/Leone25/bSmart-downloader/assets/138681357/9231acb8-50c7-43d7-8363-4be411a4110f)

**Comment by Leone25** [comment]
È un bug in una libreria che usa lo script, ma non ti preoccupare perché intanto le copie "extra" vengono ignorate

**Comment by ValeDeFra27** [comment]
Ah top grazie mille. Non ci credo ahaha dall'alto della mia ingoranza in informatica sono riuscito a seguire la tua guida e a far funzionare il tutto.

**Comment by ValeDeFra27** [comment]
Come non detto mi è appena saltato il download di un libro

![image](https://github.com/Leone25/bSmart-downloader/assets/138681357/e87bb5ec-78dd-47c1-b847-4fe6607cd9be)

**Comment by Leone25** [comment]
quello è un bug con la libreria dei pdf, non so come fixarlo quindi non si può fare molto

c'è la possibilità di scaricare le pagine individualmente e poi unirle dopo, per fare ciò segui queste istruzioni:

Crea una cartella chiamata temp nella cartella dove c'è lo script, e poi modificare lo script, commentando linea 109, 110, 111, 118 (essenzialmente devi aggiungere // all'inizio di ogni riga), e scommentare linea 107 (rimuovere gli //) e poi eseguire nuovamente lo script.
Installa pdftk da qui https://www.pdflabs.com/tools/pdftk-the-pdf-toolkit/ , la versione gratuita è sufficiente. Una volta installato, esegui il comando `node merge.js`, ti dovrebbe restituire un comando piuttosto lungo che inizia con `pdftk` e termina con `cat pog.pdf`, selezionalo tutto e copialo, adesso cambia la cartella scrivendo nel terminale (lo stesso dove hai fatto girare lo script) `cd temp`, e poi incolla ed esegui il comando che hai copiato prima, dovrebbe comparire nella cartella il pdf completo sotto forma di `pog.pdf`.

Ricordati che se vuoi scaricare un libro diverso devi svuotare la cartella temp ogni volta

**Comment by ValeDeFra27** [comment]
Grazie mille, gentilissimo. Ci proverò.
