### ISSUE TITLE
Merge request

### ISSUE THREAD

**Issue by fedcal** [Leone25/bSmart-downloader#19]
Ho fatto un fork del progetto per creare un loop che consenta di scaricare più libri alla volta. Vorrei fare una Merge request, però mi sa che devi cambiare i permessi del repository

**Comment by Leone25** [comment]
devi creare una pull request, basta che vai sulla pagina della tua fork, apri il branch da unire e premere il pulsante in alto

**Comment by Leone25** [comment]
ho guardato anche velocemente il codice che hai fatto te, non mi ispira molto perchè alla fine richiede di reinserire tutti i dati, che non ha molto senso, a quel punto si faceva prima a ri-lanciare lo script ogni volta...

**Comment by fedcal** [comment]
Ok modifico il ciclo facendo rilanciare solo l'id.

**Comment by fedcal** [comment]
Aperta, ho gestito anche quando l'esito è 404 e non uguale a 200
