### ISSUE TITLE
Count to infinity

### ISSUE THREAD

**Issue by easymax82** [Leone25/bSmart-downloader#2]
Ciao, ho dei problemi nel funzionamento del programma. Inserisco numero del libro ed auth_code corretti ma tutte le volte in output ho un conteggio che non termina mai. Solo una volta sono riuscito a scaricare un libro ed, in quel caso, veniva indicata correttamente la percentuale di download. 
In tutti gli altri casi ho una stampa infinita di numeri (ben oltre il numero di pagine del libro stesso).
Hai idee su quale possa essere il problema?
Ho capito che vengono scaricati correttamente i libri che hanno come url qualcosa del tipo mybsmart.it/#/books/18554?revision=1 in quelli in cui manca la parte "revision=1" parte il conteggio infinito e nulla viene scaricato.
 
Mi auto rispondo: necessario sostituire, in quel caso, l'url 
https://api.bsmart.it/api/v5/books/{bookId}/1/... 
con 
https://api.bsmart.it/api/v5/books/{bookId}/0/... 

Grazie

**Comment by Leone25** [comment]
Ciao!

Devo ammettere che non comprendo molto come funziona il codice di bsmart e per tanto ho dedicato gran parte del tempo a decriptare i file e non mi sono dedicato molto a come funziona l'api di per se.
Da quanto mi sembra di aver capito il numero che tu hai cambiato semplicemente cambia l'endpoint/server che elabora la richiesta e quindi non dovrebbe avere influenza su che risultato ti dovrebbe dare, ma da quanto mi riporti sembra non essere così :L dovrei seriamente dedicarci più tempo, ma per adesso direi che alla peggio segno qualcosa sul readme.

Se per caso scopri qualcosa te, e/o riesci ad implementare qualcosa, creat tramquillamente un altro issue or una pull up request e così gli do uno sguardo ed unisco.

Grazie comunque della segnalazione

**Comment by easymax82** [comment]
Ciao,
perfetto.
Probabilmente alcuni testi fanno riferimento ad una certa URL ed altri ad
un'altra. L'ho scoperto dalla console di Chrome.
Per il momento mi sono segnato anche io la cosa, in modo da ricordarmene in
futuro.
Complimenti per l'ottimo lavoro!
Grazie

Il giorno ven 17 set 2021 alle ore 20:15 Enrico ***@***.***>
ha scritto:

**Comment by Leone25** [comment]
Di niente, grazie a te
