### ISSUE TITLE
Codice non trovato

### ISSUE THREAD

**Issue by fedcal** [Leone25/bSmart-downloader#20]
Anche se nella lista compare un codice di un libro e lo provi a scaricare, non viene scaricato. Provedderò comunque a fare un loop per poter provare a scaricare un altro libro o a reinserire il codice, nel caso in cui si inserisca un codice sbagliato.

**Comment by Leone25** [comment]
puoi dare più dettagli perfavore?

**Comment by fedcal** [comment]
![image](https://github.com/Leone25/bSmart-downloader/assets/48207082/1d9a03ae-d346-4cd7-8ba4-fc8d6d66ea23)

**Comment by Leone25** [comment]
hmm, strano, si tratta di un libro che hai attivato te o di uno della classe?

**Comment by fedcal** [comment]
Chiedendo a mio fratello, non si ricorda per quale motivo quel libro si trovi tra i suoi. Quindi indagherò maggiormente sull'errore.

**Comment by Leone25** [comment]
probabilmente quel libro è uno dei libri che vengono resi disponibili in preview prima dell'inzio della scuola e che poi vengono bloccati ( a meno che non paghi ) e quello è ciò che sta accadendo
