### ISSUE TITLE
anteprima libri bsmart

### ISSUE THREAD

**Issue by sefirothmorpheus** [Leone25/bSmart-downloader#24]
per qualche periodo, sarà possibile visualizzare in anteprima i libri completi di alcune novità per il 2024 (che saranno disponibili su bsmart da settembre/ottobre 2024)
nel seguente link un esempio:

https://copertine.hoepli.it/hoepliscuola/1548-Lughezzani_Clippy_Cloud_Plus_Programmazione/index.html

potresti creare un tool in modo che scarichi il libro dall'anteprima hoepli?

**Comment by Leone25** [comment]
sono certo che sia possibile, ma attualmente non ho tempo ne interesse a sviluppare nuovi tool del genere, mispiace

probabilmente avrai più fortuna chiedendo qui https://github.com/FelixFrog/pdfgrabber
