### ISSUE TITLE
errore "bad cookie" una volta inserito il token

### ISSUE THREAD

**Issue by alepecce14** [Leone25/bSmart-downloader#25]
ogni volta che inserisco il valore del cookie, ricevo l'errore "bad cookie" senza poter arrivare alla lista dei libri. Ho dato un'occhiata negli issues risolti e ho utilizzato, come consigliato, un'estensione per estrarre il valore del cookie in modo che fosse corretto, ma non ha risolto il problema.

**Comment by Leone25** [comment]
hm, strano, prova a fare un console log dello stato della richiesta dell'utente, prima della condizione che porta al messaggio di bad cookie

**Comment by alepecce14** [comment]
ok, dovrei aver risolto il problema del bad cookie: il token veniva inserito come stringa con le virgolette all’inizio e alla fine.

provando a inserire il token senza virgolette, pero

**Comment by Leone25** [comment]
ah ok
