### ISSUE TITLE
scaricare contenuti digitali (audio e viedo)

### ISSUE THREAD

**Issue by sefirothmorpheus** [Leone25/bSmart-downloader#27]
ciao
si potrebbe fare qualcosa per scaricare anche i contenuti digitali (audio e video) associati ai libri?

**Comment by Leone25** [comment]
per quelli, generalmente non sono criptati, wuindi é più semplice se apri il lettore web, poi apri gli strumenti per sviluppatori (f12) e guardi sulla pagina di rete. Filtri per contenuti multimendiali e poi apri il video/audio, dovrebbe comparire una richiesta per un file video o audio. A questo punto fai tasto destro e apri in un altra scheda. Da li fai ctrl+s e salvi dove vuoi

**Comment by sefirothmorpheus** [comment]
ciao, si, conoscevo questo metodo, ma pensavo si potesse fare qualcosa in automatico, in quanto per i libri di lingue gli audio sono in genere tanti, quindi scaricarli uno ad uno prende troppo tempo.
cmq, grazie lo stesso per il tuo lavoro su questo e altri tool

**Comment by Leone25** [comment]
ho caricato un aggiornamento

adesso eseguendo `node index.js --resources`, e poi seguendo la procedura standard scaricherà tutte le risorse del libro disponibili

attento che non fa distinzioni, quindi ci possono essere tantissimi file, e con file più grandi (tipo i video) potrebbe sembrare che lo script si blocchi, ma comunque stà pensando, dagli tempo.

**Comment by sefirothmorpheus** [comment]
ciao, mi da errore per scaricare i contenuti su un libro in particolare:

![Immagine](https://github.com/user-attachments/assets/fb10828a-23e2-4b49-ac44-3ab45ad5fac0)

il libro è "Nicht nur Literatur NEU" e lo trovi in anteprima fino al 30 Ottobre, lo trovi ad esempio in questa scuola:

città
Trescore Balneario

nome scuola
"LORENZO FEDERICI"

classe
4BL LICEO LINGUISTICO

puoi guardarci per favore?
