### ISSUE TITLE
Non riesco a trovare l'Auth Token

### ISSUE THREAD

**Issue by comleoita** [Leone25/bSmart-downloader#3]
Ciao,
Non riesco a trovare l'auth token di bsmart

**Comment by Leone25** [comment]
Ciao!

Il tuo problema (da esperienza) può essere causato da varie cose:
1. non hai disabilitato le cache
2. stai girando su un browser basato su chromium (ultimamente da problemi), soluzione, usa firefox

prova a controllare quelle due cose, se nulla va poi chiedi di nuovo che vediamo di trovare il problema e risolverlo

**Comment by comleoita** [comment]
Grazie della risposta,
Il problema è che proprio non so dove andarlo a prendere l'auth token.
Ora provo a disattivare la cache e usare firefox

**Comment by comleoita** [comment]
Allora,
Ho provato a disattivare la cache e credo di aver trovato l'auth token, solo che il programma mi conta all'infinito

**Comment by Leone25** [comment]
ottimo,

il problema del conto all'infinito mi è stato reso noto, la soluzione sembra modificare linea 123 e sostituire l'1 con uno 0 (e se non va neanche quello provare con 2, 3, ecc)

**Comment by Leone25** [comment]
nessun problema
