### ISSUE TITLE
Auth Code

### ISSUE THREAD

**Issue by compasoft** [Leone25/bSmart-downloader#4]
Ciao Enrico,
Ho un problema con il programmino
non riesco proprio a trovare l'auth code
non è che mi potresti dare un esempio
Grazie
Carlo

**Comment by compasoft** [comment]
Io sono riuscito, tramite un'app modificata, a scaricare una cartella chiamata PDF, con dentro tanti file senza estensione. Credo sia quella come faccio a decriptarli?

**Comment by Leone25** [comment]
Ciao,
per l'auth code apri il libro nel browser (ti consiglio firefox), premi f12 appena ti si apre la pagina, nel menu che ti si apre clicca poi sulla pagina di rete (o network), adesso clicca su disabilita cache per disabilitare le cache e abilita il filtro fetch/xhr (basta che ci clicco sopra), poi in basso ci dovrebbe essere una richiesta che inizia con "links?per_page=500&page=1", clicca quella, scorri in basso nel menu che si apre, il tuo `auth_code` si trova da quelle parti sotto i "request headers"

**Comment by compasoft** [comment]
Funziona,
Sei un grande
