### ISSUE TITLE
bSmart cookies problem

### ISSUE THREAD

**Issue by AmilyHope** [Leone25/bSmart-downloader#8]
Hello thanks for your work.
I tried to follow the guide for download books from bsmart but I'm stuck at point 3.
I opened the dev tools and application (Chromium) tab, I click on Cookie, then https://my.bsmart.it, but I can't sede and copy the cookie called _bsw_session_v1_production to the terminal.
Could you show me where to retrieve the cookie and how to copy it to the terminal.

thank you so much!

**Comment by Leone25** [comment]
sure, here is what I see, the big red rectangle at the bottom is where you should copy the cookie from
![Screenshot 2022-11-05 175103](https://user-images.githubusercontent.com/39310565/200131822-5d2773c0-d65b-4127-9593-2e391e58450b.png)

**Comment by AmilyHope** [comment]
Hy, thank you for answer.
I tried this solution but
1) the valute of cookie change every time i refresh the page 
2) i copy this valute but when i paste (right click of mouse) automatically It pastes several times on the terminal.
Is It normal point 1)?
Is It normal point 2)?

I use Windows, Is this a problem?
Can you give me some suggestion for these issues?

Thank you!

**Comment by Leone25** [comment]
2 yes, absolutely i need to replace that library but can't be bothered rn, the code still receives the right code anyway

1 probably, just keep the tab open and don't refresh it while you download books, as long as it works it's fine

**Comment by AmilyHope** [comment]
![i1](https://user-images.githubusercontent.com/117513900/200133573-b3f00b71-2c59-4d2b-95f2-b491a2f5cfbc.png)
![i2](https://user-images.githubusercontent.com/117513900/200133574-594ece84-d246-48c3-9e18-a5d201031fba.png)
Hy, thank you. 
The value of cookie was too long so I tried to change the value of the cookie in "new" and i write "new" on the terminal in node index.js but the terminal sais me "bad cookie".
If you can suggest an other idea , I thank you!

**Comment by Leone25** [comment]
That . . . Is not how that works, the cookie is not used to connect to the webpage, but rather it's to "pretent" to be the webpage, so if you modify it in the page it would be of any use.

You need to copypaste the cookie as is. Even if it's a mess, just copy and paste it, it should work

**Comment by AmilyHope** [comment]
![i3](https://user-images.githubusercontent.com/117513900/200135101-788daf19-d780-44d9-bfda-5023719fff1c.png)
Hy, thank you. I tried as you suggest :
i didn't changed the value of cookie, i copy and past it on terminal (right click of the mouse) but as i show you, it doesn't work.
i don't understand what it's the problem.
If you fix it, i try again.
thank you for all!

**Comment by Leone25** [comment]
Try disabling "mostra url decodificato"

**Comment by Wallace089** [comment]
Hello there ;

Thanks for your contribution; I have got some questions if you don't mind:

Whenever I copy and paste the cookie, it just stuck, but when I hit "Enter," it successfully recognizes my list of books then, when I enter the ID of the book, it throws this error "can not read property of undefined id"

Should I wait and not hit enter?

**Comment by Wallace089** [comment]
> Hello there ;
> 
> Thanks for your contribution; I have got some questions if you don't mind:
> 
> Whenever I copy and paste the cookie, it just stuck, but when I hit "Enter," it successfully recognizes my list of books then, when I enter the ID of the book, it throws this error "can not read property of undefined id"
> 
> Should I wait and not hit enter?

The problems is fixed , when I hit enter it adds the number in "cookie" section , I deleted that and re-entered and it works fine

Thank you  very much !

Just have one request; I tried this on another website that is supported by "Bsmart" and as expected it did not work! is there any possibility to work on those too in the future?

**Comment by Wallace089** [comment]
Just some suggestions:

1- if it would download the book's audio, it would be handy.
2-if other sites that are supported by "B-smart," like "Eli-Online," "ehachettefle", etc. be added, it would be perfect
3-All in All, thanks for your great contribution

**Comment by Leone25** [comment]
1. no idea where to grab those from but i'm sure it could be done
2. for scripts for other websites you can check my account, i have a couple, otherwise it's likely someone else already made it, worst case scenario you have a chance to learn something new and you can make it your self.
3. you are welcome
